name: "Polaris Incremental Scan"

on:
  pull_request

jobs:
  build:
    runs-on: macos-latest
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      POLARIS_FF_ENABLE_COVERITY_INCREMENTAL: true
      GH_SECRET: ${{ secrets.GH_SECRET }}
      
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    # Get the list of files to analyze 
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
       for changed_file in ${{ steps.files.outputs.all }}; do
         echo ${changed_file} >> files-to-scan.txt
       done
      
    # Running Polaris - Incremental mode     
    - name: Polaris (SAST) - Incremental
      if: ${{github.event_name == 'pull_request'}}
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d /tmp -jo polaris_cli-linux64.zip
        /tmp/polaris analyze -w --coverity-ignore-capture-failure --incremental files-to-scan.txt | tee polaris-output.txt    
 
    # Convert Polaris to SARIF
    - name: polaris_sarif
      run: |
        node scripts/SARIF/cov-format-sarif-for-github.js --inputFile .synopsys/polaris/data/coverity/2022.6.0/idir/incremental-results/incremental-results.json --repoName sig-demo/iGoat-Swift --checkoutPath sig-demo/iGoat-Swift /iGoat-Swift/ $GH_SECRET --outputFile GitHubSarif.json
        
  # Upload Polaris findings to GitHub Actions
    - name: Upload Polaris results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: GitHubSarif.json
